### PR TITLE
Update query.sparql

### PR DESCRIPTION
**Pull request by so9q**
This change removes the bulk of false positives and gives ~8000 matches for english. There is still room for improvement, but this is a good start that won't drive the player (me!) crazy.

Note I had to change the language option to only return one language at a time because it times out otherwise. Can you run the query once for each language?

### CODE REVIEW

**Comment by Nudin** [comment]
Thanks for the sophisticated improvement of the query! This should indeed improve the usability and fun-factor of the tool a lot, especially for English.
The limit to English due to server timeouts is however a bit of an issue. Could it be possible to have two queries one for English and one for all other languages? I quickly tried but did not succeed. Maybe the query could be optimized?
In anyway the back-end script has to be improved for this, starting with migrating it to SQLAlchemy. I started with that but am not finished.

**Comment by so9q** [comment]
I'm not sure what you mean exactly. The query there works without timing out. The old one works for all other languages. Maybe you can add an if statement to choose this if english and fall back to the other with else?
I tried optimizing with subquery but to no avail. I asked others for help here: https://www.wikidata.org/wiki/Wikidata:Request_a_query#Improved_MachtSinn_query_times_out
I don't think grouping all languages in one query is a way forward with WDQS in its current state.

I did not try the de-language version but glancing at the statistics (1900 bad) and (1000 matched) it seems that query can be improved as well.

I don't know what SQLAlchemy is. Will look it up...

**Comment by Nudin** [comment]
Since I sadly won't have time to do this properly (see #24) I now did a run of your query manually for the English version only and cleaned the old English matches up.
So it should be usable in English for the next time.

If anyone is interested in improving the backend script (whether based on SQLAlchemy or not, I don't mind) it would be highly appreciated.

@so9q Maybe you can write to the project chat and/or lexeme-talk page to inform people that English is now better usable so that more people help on the >7000 matches to check?!

**Comment by so9q** [comment]
Done. Big thanks! The english version is now very much improved :)

**Comment by so9q** [comment]
https://www.wikidata.org/wiki/Wikidata_talk:Lexicographical_data#MachtSinn_update_and_help_wanted

**Comment by Nudin** [comment]
I now improved the backend to allow multiple queries for different languages and one fallback for the others. I included you query as the query for english.
Thanks again!

**Pull request closed without merging**
