### PR TITLE
small CSS update

### PR DESCRIPTION
**Pull request by DanD16**
Solves #6 . Please let me know what you think about it or what should be changed (tried to keep the minimalistic look and feel of the page). I could not trigger the "previous" section, therefore that one is not inspected if the styling is appropriate!

### CODE REVIEW

**Comment by Nudin** [comment]
Thanks! This definitely is an improvement. The "minimalistic look and feel" is mostly due to me not being good in design but I'm also very ok with keeping that.

One thing I don't like is that the buttons now have different heights – at least on by browser:
Bildschirmfoto zu 2019-10-06 21-49-49

Can we make them of identical size? Making them bigger is probably a good idea anyway, since it's easier to click them and more accessible.

**Comment by DanD16** [comment]
Hi there! I'll check it this evening, I guess due to different screen sizes, because on mine was equal height for all of them.

**Comment by DanD16** [comment]
I've updated your new links as well, it was broken on my different css settings. Well, the buttons... I tried to check them in responsive views, in different browsers, but everything was fine, so I've just increased the sizes a bit more, please let me know if it's still not working properly.

**Comment by Nudin** [comment]
I still get different sizes. Decreasing the padding from `0.6em` to `0.5em` fixes the issue.
I assume the origin of the issue is that I have a bigger font size. To to Zoom by Ctr+/-.

Maybe the easiest way to assure that the issue is solved for everyone it to change the labels. Having them consistent might anyway be better understandable?

**Comment by DanD16** [comment]
Weird, I still couldn't reproduce. Anyhow, could you please elaborate what you have in mind? Based on your request today, or tomorrow I'll try to solve it. Sorry if I seem clumsy, this is the first time I'm working on a real repo :D

**Comment by Nudin** [comment]
No need for apologies, everything is fine and git is hard.
Since I wanted to have the improvements deployed I merged your branch and changed the labels and the margin to fix the issue for me, but feel free to create a follow up-PR!

**Comment by Nudin** [comment]
@DDuplinszki a friend of mine who is UX-Designer created a Mokup about an alternative design. Would you be interested in trying to implement it?

**Comment by DanD16** [comment]
Hi, that's great news! Yes I would like to try it! How would you like to send the doc to me?

Also, if you don't mind, the other pull request about the short-keys seems sort of inactive, so I started to work on that one, I'm actually pretty close to the solution, I've just ran into a bug. For now, I'll prioritise the new design though.

**Pull request merged**
