### PR TITLE
Add the time of database updates to the statistics page

### PR DESCRIPTION
**Pull request by Antsthebul**
Hopefullly this is alongs the lines of what you all had in mind. I Created display for date/time in the html file. Added in supporting css. Refactored all update queries in app.py, save() and reject(), to also record time-of-update. Added db_update module to add in new timestamp column. Also did some very slightl refactoring in the htm as to not break it.

### CODE REVIEW

**Comment by Nudin** [comment]
Hi, thanks for the PR. Sadly I think you misunderstood the issue or something about the code. MachtSinn regularly runs a few SPARQL queries that search for potential matches and save them in the local database. The web tool then displays those and if the user agrees to them, they get saved in Wikidata and marks them as 'done' in the database. The idea was to save and display the time the database was updated by the SPARQL queries, so that it's visible if the SPARQL queries or something else in the backend fails.
What your code does so far is to save the time when a match has last been marked as done, that is the last time someone clicked on "match".

Do you want to improve the PR?

**Comment by Antsthebul** [comment]
Yeah I see what you mean. I definitely misunderstood the code, I am now learning about RDF and SPARSQL, so I still would like to contribute if that's ok. If not thanks for taking time to review my PR.

**Comment by Nudin** [comment]
No worries. You don't have to understand much about SPARQL or RDF for this, you should find everything you need (additional to what you already did) in the file `backend.py`. This fill first creates the database tables (lines 50-120, create the new one here too) and then runs the SPARQL queries and puts the results into the tables (217-258). That is where you should check if it was successful (241-253) and if so save the current time.

**Comment by Antsthebul** [comment]
Ah I think im begining to understand. I spent a whole lot of time researching RDF and i didnt even need it HAHA. Its pretty cool though actually, so im glad i checked it out. I think i want to start using RDF in the future. I appreciate your patience and feedback. Not sure if i got closer to what you were looking for, still a little unsure about the exact logic, but i do understand the code more than before. Timestamp column created when tables are creatred, then saved for each entry of a match item (sparql queries), and only displayed if there is a row in the lang table that matches the row in "matches".

**Comment by Antsthebul** [comment]
https://github.com/Nudin/makesense/pull/80

**Pull request closed without merging**
