### PR TITLE
fixed css that caused button to overflow the margin

### PR DESCRIPTION
**Pull request by Ainali**
it stuck out on the bottom and looked out of place

### CODE REVIEW

**Review by waldyrious — APPROVED** [review]
I can confirm this fixes the issue on my side.

Before:
Screenshot 2020-03-06 at 11 15 14

After:
Screenshot 2020-03-06 at 11 16 33

**Comment by waldyrious** [comment]
@Ainali why not simply removing the margin-bottom rule altogether? Here's what I see if I do that:

Screenshot 2020-03-06 at 11 19 10

**Comment by Nudin** [comment]
Hmm, I'm a bit uncertain – this actually was "not a bug but a feature". ;) It has been part of the [design](https://www.figma.com/file/5FJOap1SfbZ2769GQOCjfM/MachtSinn---WikidataGame?node-id=0%3A1) the UX person created.
But since it's already two people who are confused, maybe we should get rid of it?

On the other side: it currently isn't correctly aligned with the borderline to the center of the buttons – maybe fixing that  would be an alternative?
Any thoughts?

**Comment by waldyrious** [comment]
>  But since it's already two people who are confused, maybe we should get rid of it?

Yes, please 😅 it looks like something is broken, rather than an intentional design.

> isn't correctly aligned with the borderline to the center of the buttons

Not sure I understand what you mean by that.

**Comment by Ainali** [comment]
> @Ainali why not simply removing the margin-bottom rule altogether? Here's what I see if I do that:
> 
> Screenshot 2020-03-06 at 11 19 10

That sounds like a smart idea!

**Pull request merged**
